export  const Imgs={
    Homegif:require('../src/images/empty_cart.gif'),
    logo:require('../src/images/imgred.png'),
    menuicon:require('../src/images/menu1.jpg'),
    homeicon:require('../src/images/home.png'),
    profileicon:require('../src/images/profile.png'),
    abouticon:require('../src/images/about.jpg'),
    contacticon:require('../src/images/contact.png'),
    logouticon:require('../src/images/logout.jpg'),
    aboutgif:require('../src/images/online1.gif'),
    contactgif:require('../src/images/contactgif.gif'),
    pen:require('../src/images/pen.png'),
    mobile:require('../src/images/smartphone.png'),
    envelope:require('../src/images/envelope.png'),
    password:require('../src/images/password.png'),
    back:require('../src/images/back.gif'),
    loader:require('../src/images/Loader.gif'),
    gear:require('../src/images/gear.gif'),
    slider1:require('../src/images/slider1.jpg'),
    slider2:require('../src/images/slider2.jpg'),
    slider3:require('../src/images/slider3.jpg'),
    slider4:require('../src/images/slider4.jpg'),
    slider5:require('../src/images/slider5.jpg'),
    slider6:require('../src/images/slider6.png'),

}